apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lm8w3fz9o-python
  janus-idp.io/tekton: lm8w3fz9o-python
  backstage.io/kubernetes-id: lm8w3fz9o-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lm8w3fz9o-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
