apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lm8w3fz9o-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lm8w3fz9o-python 
  name: lm8w3fz9o-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lm8w3fz9o-python 
